export { ScriptedModel, ScriptedModelExhaustedError } from "./adapters/scripted-model.js";
export {
  createOpenAiCompatibleModelPortFromEnv,
  OpenAiCompatibleModelConfigurationError,
  OpenAiCompatibleModelPort,
  OpenAiCompatibleModelResponseError,
} from "./adapters/openai-compatible-model.js";
export type {
  AiSdkStreamPart,
  AiSdkStreamTextOptions,
  AiSdkStreamTextResult,
  AiSdkUsage,
  OpenAiCompatibleModelConfig,
  OpenAiCompatibleModelDependencies,
  OpenAiCompatibleModelEnvironment,
} from "./adapters/openai-compatible-model.js";
export {
  IllegalPlanApprovalStateError,
  IllegalEvidenceStateError,
  IllegalSourceReadStateError,
  InvalidClaimCommandError,
  InvalidEvidenceCommandError,
  InvalidSourceReadCommandError,
  InvalidSourceScopeError,
  InvalidPlanApprovalCommandError,
  PlanApprovalConflictError,
  ClaimEvidenceNotAvailableError,
  EvidenceObservationNotAvailableError,
  EvidencePersistenceError,
  EvidenceWriteConflictError,
  EvidenceGateBlockedError,
  IllegalLearningArtifactPublicationStateError,
  IllegalLearningArtifactStateError,
  IllegalPublicationApprovalStateError,
  InvalidLearningArtifactCommandError,
  InvalidPublicationApprovalCommandError,
  LearningArtifactDraftConflictError,
  LearningArtifactDraftError,
  LearningArtifactPublicationError,
  ModelViewTooLargeError,
  PublicationApprovalConflictError,
  ResearchAgentRuntime,
  ResearchLoopError,
  SourceReadConflictError,
  SourceReadPersistenceError,
  SourceReadRunNotFoundError,
  StalePublicationApprovalError,
  StalePlanApprovalError,
} from "./application/research-agent-runtime.js";
export { formatRunTrace } from "./application/trace-format.js";
export { runCli } from "./cli.js";
export { PrivateRuntimeHomeError } from "./infrastructure/private-runtime-home.js";
export {
  LearningArtifactPublishError,
  PublicationTargetPreparationError,
} from "./infrastructure/learning-artifact-publisher.js";
export { EvidenceGateError, evaluateEvidenceGate } from "./domain/evidence-gate.js";
export {
  createPublicationApprovalBinding,
  renderLearningArtifact,
} from "./domain/learning-artifact.js";
export {
  createPlanApprovalBinding,
  hashCanonicalJson,
} from "./domain/integrity.js";
export type {
  Clock,
  IdGenerator,
  LearningArtifactProposalRequest,
  ModelCallOptions,
  ModelPort,
  PlanRequest,
  SourceSearchPort,
  SourceSearchRequest,
  RetryScheduler,
} from "./application/ports.js";
export {
  InfrastructureFailureError,
  ModelGenerationAbortedError,
} from "./application/ports.js";
export type {
  AdvanceResearchCommand,
  ApprovePlanCommand,
  ApprovePublicationCommand,
  CreateRunCommand,
  InspectRunCommand,
  OpenRuntimeOptions,
  ProposeLearningArtifactCommand,
  PublishLearningArtifactCommand,
  ReadSourceCommand,
  RecordClaimCommand,
  RecordEvidenceCommand,
  RebuildRunProjectionCommand,
  ResearchLoopLifecycleHooks,
  TraceRunCommand,
} from "./application/research-agent-runtime.js";
export type {
  ArtifactReference,
  Claim,
  CompletedRunState,
  EvidenceBackedRunStateData,
  PlanApprovalBinding,
  PlanApprovalReceipt,
  ReadSourceRequest,
  ResearchPlan,
  ResearchRunEvent,
  ResearchRunState,
  ResearchingRunState,
  PersistedSourceSnapshot,
  RunBudget,
  RunProjection,
  RunTrace,
  RunTraceEvent,
  RequestedSourceScope,
  SourceRootIdentity,
  SourceAccessDenialCode,
  SourceAccessFailureCode,
  SourceReadObservation,
  SucceededSourceReadObservation,
  DeniedSourceReadObservation,
  EvidenceRecord,
  ExperimentIdentity,
  FailedSourceReadObservation,
  SourceSnapshotReference,
  SourceScope,
  LearningArtifactProposal,
  ModelTurn,
  ModelUsage,
  ModelView,
  ModelViewEvidence,
  RemainingRunBudget,
  ResearchToolIntent,
  ResearchToolObservation,
  SourceSearchMatch,
  BudgetExhaustedRunState,
  RetryPolicy,
  RetryAttempt,
  NormalizedFailure,
  ResearchCompleteRunState,
  PublicationApprovalBinding,
  PublicationApprovalReceipt,
  PublicationTarget,
  PublishedLearningArtifact,
  ReadyToPublishRunState,
  WaitingPublicationApprovalRunState,
} from "./domain/types.js";
